package co.electrovan.structse.modelo;

import java.util.Date;

/**
 * EventosCambioClaveTbl generated by hbm2java
 */
public class EventosCambioClaveTbl implements java.io.Serializable {

	private Integer idCambioClave;
	private String usuario;
	private String nuevaClave;
	private Date fechaSolicitud;
	private boolean estadoSolicitud;

	public EventosCambioClaveTbl() {
	}

	public EventosCambioClaveTbl(String usuario, String nuevaClave,
			Date fechaSolicitud, boolean estadoSolicitud) {
		this.usuario = usuario;
		this.nuevaClave = nuevaClave;
		this.fechaSolicitud = fechaSolicitud;
		this.estadoSolicitud = estadoSolicitud;
	}

	public Integer getIdCambioClave() {
		return this.idCambioClave;
	}

	public void setIdCambioClave(Integer idCambioClave) {
		this.idCambioClave = idCambioClave;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getNuevaClave() {
		return this.nuevaClave;
	}

	public void setNuevaClave(String nuevaClave) {
		this.nuevaClave = nuevaClave;
	}

	public Date getFechaSolicitud() {
		return this.fechaSolicitud;
	}

	public void setFechaSolicitud(Date fechaSolicitud) {
		this.fechaSolicitud = fechaSolicitud;
	}

	public boolean isEstadoSolicitud() {
		return this.estadoSolicitud;
	}

	public void setEstadoSolicitud(boolean estadoSolicitud) {
		this.estadoSolicitud = estadoSolicitud;
	}

}
